<h3>Introducing NumPy</h3> <br>

In [2]:
import numpy as np

<h3>Scalars</h3><br>
Instead of Python’s int, you have access to types like uint8, int8, uint16, int16, and so on.

In [3]:
s = np.array(5)

In [8]:
s.shape

()

In [9]:
x = s + 3

### Vectors


In [5]:
v = np.array([1,2,3])

In [7]:
v.shape

(3,)

In [8]:
x = v[1]

### Matrices

In [9]:
m = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [10]:
m[1][2]

6

### Tensors

In [11]:
t = np.array([[[[1],[2]],[[3],[4]],[[5],[6]]],[[[7],[8]],\
    [[9],[10]],[[11],[12]]],[[[13],[14]],[[15],[16]],[[17],[17]]]])

### Changing Shapes

In [13]:
v = np.array([1,2,3,4])

In [16]:
x = v.reshape(1,4)

In [17]:
x = v.reshape(4,1)

## Element-wise operations
### The Python way

In [20]:
values = [1,2,3,4,5]
for i in range(len(values)):
    values[i] += 5

### The NumPy way

In [18]:
values = [1,2,3,4,5]
values = np.array(values) + 5

In [ ]:
x = np.multiply(values, 5)
x

<h3>Element-wise Matrix Operations</h3><br>

In [25]:
a = np.array([[1,3],[5,7]])
a

array([[1, 3],
       [5, 7]])

In [26]:
b = np.array([[2,4],[6,8]])
b

array([[2, 4],
       [6, 8]])

In [ ]:
a + b

In [27]:
a = np.array([[1,3],[5,7]])
a

array([[1, 3],
       [5, 7]])

In [28]:
c = np.array([[2,3,6],[4,5,9],[1,8,7]])
c

array([[2, 3, 6],
       [4, 5, 9],
       [1, 8, 7]])

In [29]:
a.shape

(2, 2)

In [30]:
c.shape

(3, 3)

In [31]:
a + c

ValueError: operands could not be broadcast together with shapes (2,2) (3,3) 

<h2>NumPy Matrix Multiplication</h2><br>

<h3>Element-wise Multiplication</h3><br>
 or the * operator. Just to revisit, it would look like this:

In [36]:
np.multiply(m, n)   # equivalent to m * n

array([[ 0.25,  1.  ,  2.25],
       [ 4.  ,  6.25,  9.  ]])

<h3>Matrix Product</h3><br>

<h3>NumPy's dot function</h3><br>
You may sometimes see NumPy's dot function in places where you would expect a matmul. It turns out that the results of dot and matmul are the same if the matrices are two dimensional.

So these two results are equivalent:

In [44]:
a = np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [45]:
np.dot(a,a)

array([[ 7, 10],
       [15, 22]])

In [46]:
a.dot(a)  # you can call `dot` directly on the `ndarray`

array([[ 7, 10],
       [15, 22]])

In [47]:
np.matmul(a,a)

array([[ 7, 10],
       [15, 22]])

While these functions return the same results for two dimensional data, you should be careful about which you choose when working with other data shapes. You can read more about the differences, and find links to other NumPy functions, in the matmul and dot documentation.

<h3>Transpose</h3><br>
Getting the transpose of a matrix is really easy in NumPy. Simply access its T attribute. There is also a transpose() function which returns the same thing, but you’ll rarely see that used anywhere because typing T is so much easier. :)

For example:

In [49]:
m = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
m

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [50]:
m.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

NumPy does this without actually moving any data in memory - it simply changes the way it indexes the original matrix - so it’s quite efficient.

However, that also means you need to be careful with how you modify objects, because they are sharing the same data. For example, with the same matrix m from above, let's make a new variable m_t that stores m's transpose. Then look what happens if we modify a value in m_t:

In [51]:
m_t = m.T
m_t[3][1] = 200
m_t
m

array([[  1,   2,   3,   4],
       [  5,   6,   7, 200],
       [  9,  10,  11,  12]])

Notice how it modified both the transpose and the original matrix, too! That's because they are sharing the same copy of data. So remember to consider the transpose just as a different view of your matrix, rather than a different matrix entirely.

A real use case
I don't want to get into too many details about neural networks because you haven't covered them yet, but there is one place you will almost certainly end up using a transpose, or at least thinking about it.

Let's say you have the following two matrices, called inputs and weights,

In [52]:
inputs = np.array([[-0.27,  0.45,  0.64, 0.31]])
inputs

array([[-0.27,  0.45,  0.64,  0.31]])

In [53]:
inputs.shape

(1, 4)

In [54]:
weights = np.array([[0.02, 0.001, -0.03, 0.036], \
    [0.04, -0.003, 0.025, 0.009], [0.012, -0.045, 0.28, -0.067]])

weights

array([[ 0.02 ,  0.001, -0.03 ,  0.036],
       [ 0.04 , -0.003,  0.025,  0.009],
       [ 0.012, -0.045,  0.28 , -0.067]])

In [55]:
weights.shape

(3, 4)

I won't go into what they're for because you'll learn about them later, but you're going to end up wanting to find the matrix product of these two matrices.

If you try it like they are now, you get an error:

In [56]:
np.matmul(inputs, weights)

ValueError: shapes (1,4) and (3,4) not aligned: 4 (dim 1) != 3 (dim 0)

If you did the matrix multiplication lesson, then you've seen this error before. It's complaining of incompatible shapes because the number of columns in the left matrix, 4, does not equal the number of rows in the right matrix, 3.

So that doesn't work, but notice if you take the transpose of the weights matrix, it will:

In [57]:
np.matmul(inputs, weights.T)

array([[-0.01299,  0.00664,  0.13494]])

It also works if you take the transpose of inputs instead and swap their order, like we showed in the video:

In [58]:
np.matmul(weights, inputs.T)

array([[-0.01299],
       [ 0.00664],
       [ 0.13494]])

The two answers are transposes of each other, so which multiplication you use really just depends on the shape you want for the output.